"""initial schema

Revision ID: 78e0b4f03830
Revises:
Create Date: 2026-09-08 12:51:42.785269

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78e0b4f03830"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("has_activated_once", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("activation_token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("password_token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("access_token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("refresh_token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "vip_client",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("client_code", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vip_client_client_code"), "vip_client", ["client_code"], unique=True)
    op.create_index(op.f("ix_vip_client_email"), "vip_client", ["email"], unique=True)
    op.create_index(op.f("ix_vip_client_phone"), "vip_client", ["phone"], unique=True)
    op.create_table(
        "appointments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "REQUESTED",
                "QUOTED",
                "SCHEDULED",
                "COMPLETED",
                "CANCELED",
                name="appointment_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "appointment_type",
            sa.Enum("TATTOO", "PIERCING", name="appointment_type_enum"),
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("placement", sa.String(length=255), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column("size", sa.String(length=255), nullable=True),
        sa.Column("current_session", sa.Integer(), nullable=True),
        sa.Column("total_sessions", sa.Integer(), nullable=True),
        sa.Column("color", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("deposit_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("vip_client_id", sa.UUID(), nullable=True),
        sa.Column("client_name", sa.String(length=255), nullable=True),
        sa.Column("client_email", sa.String(length=255), nullable=True),
        sa.Column("client_phone", sa.String(length=50), nullable=True),
        sa.Column("referral_code", sa.String(length=50), nullable=True),
        sa.Column("is_posted_on_socials", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("observations", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            """
            vip_client_id IS NOT NULL
            OR (
                client_name IS NOT NULL
                AND client_email IS NOT NULL
                AND client_phone IS NOT NULL
            )
            """,
            name="check_client_info_valid",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_appointments_appointment_type"), "appointments", ["appointment_type"], unique=False
    )
    op.create_index(op.f("ix_appointments_client_email"), "appointments", ["client_email"], unique=False)
    op.create_index(op.f("ix_appointments_client_phone"), "appointments", ["client_phone"], unique=False)
    op.create_index(op.f("ix_appointments_color"), "appointments", ["color"], unique=False)
    op.create_index(
        op.f("ix_appointments_deposit_confirmed_at"),
        "appointments",
        ["deposit_confirmed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_is_posted_on_socials"),
        "appointments",
        ["is_posted_on_socials"],
        unique=False,
    )
    op.create_index(op.f("ix_appointments_project_id"), "appointments", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_appointments_referral_code"), "appointments", ["referral_code"], unique=False
    )
    op.create_index(op.f("ix_appointments_status"), "appointments", ["status"], unique=False)
    op.create_index(op.f("ix_appointments_user_id"), "appointments", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_appointments_vip_client_id"), "appointments", ["vip_client_id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_name", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=250), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "actor_type", sa.Enum("USER", "SYSTEM", "CLIENT", name="auditactortype"), nullable=False
        ),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_type"), "audit_logs", ["actor_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_name"), "audit_logs", ["entity_name"], unique=False)
    op.create_table(
        "calendar_exceptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("calendar_of_user", sa.UUID(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "exception_type",
            sa.Enum("ALLOW", "BLOCK", name="calendar_exception_type_enum"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("end_at > start_at", name="check_calendar_exception_end_after_start"),
        sa.ForeignKeyConstraint(
            ["calendar_of_user"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendar_exceptions_calendar_of_user"),
        "calendar_exceptions",
        ["calendar_of_user"],
        unique=False,
    )
    op.create_table(
        "calendar_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("booking_window_until", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "client_credit_entry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vip_client_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "INDICATION",
                "ADDED_BY_ADMIN",
                "USED_AS_PAYMENT",
                "REVERSED_BY_ADMIN",
                name="client_credit_source_type",
            ),
            nullable=False,
        ),
        sa.Column("related_entry_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["related_entry_id"],
            ["client_credit_entry.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vip_client_id"],
            ["vip_client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_credit_entry_related_entry_id"),
        "client_credit_entry",
        ["related_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_credit_entry_source_id"), "client_credit_entry", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_client_credit_entry_vip_client_id"),
        "client_credit_entry",
        ["vip_client_id"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum("CASH", "CARD", "PIX", "CLIENT_CREDIT", name="payment_method_enum"),
            nullable=False,
        ),
        sa.Column(
            "payment_purpose",
            sa.Enum("APPOINTMENT", "DEPOSIT", "TIP", "OTHER", name="payment_purpose_enum"),
            nullable=False,
        ),
        sa.Column("vip_client_id", sa.UUID(), nullable=True),
        sa.Column("appointment_id", sa.UUID(), nullable=True),
        sa.Column("external_reference", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vip_client_id"],
            ["vip_client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_appointment_id"), "payments", ["appointment_id"], unique=False)
    op.create_index(
        op.f("ix_payments_external_reference"), "payments", ["external_reference"], unique=True
    )
    op.create_index(op.f("ix_payments_vip_client_id"), "payments", ["vip_client_id"], unique=False)
    op.create_table(
        "working_periods",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("calendar_settings_user_id", sa.UUID(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_at", sa.Time(), nullable=False),
        sa.Column("end_at", sa.Time(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("end_at > start_at", name="check_working_period_end_after_start"),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name="check_valid_weekday"),
        sa.ForeignKeyConstraint(
            ["calendar_settings_user_id"],
            ["calendar_settings.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "calendar_settings_user_id", "weekday", "start_at", "end_at", name="unique_working_period"
        ),
    )
    op.create_index(
        op.f("ix_working_periods_calendar_settings_user_id"),
        "working_periods",
        ["calendar_settings_user_id"],
        unique=False,
    )
    op.create_table(
        "refunds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "refund_status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", "CANCELED", name="refund_status_enum"),
            nullable=False,
        ),
        sa.Column(
            "refund_method",
            sa.Enum("CASH", "CARD", "PIX", "CLIENT_CREDIT", name="refund_method_enum"),
            nullable=False,
        ),
        sa.Column("vip_client_id", sa.UUID(), nullable=True),
        sa.Column("appointment_id", sa.UUID(), nullable=True),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vip_client_id"],
            ["vip_client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refunds_appointment_id"), "refunds", ["appointment_id"], unique=False)
    op.create_index(
        op.f("ix_refunds_created_by_user_id"), "refunds", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_refunds_payment_id"), "refunds", ["payment_id"], unique=False)
    op.create_index(op.f("ix_refunds_vip_client_id"), "refunds", ["vip_client_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refunds_vip_client_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_payment_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_created_by_user_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_appointment_id"), table_name="refunds")
    op.drop_table("refunds")
    op.drop_index(op.f("ix_working_periods_calendar_settings_user_id"), table_name="working_periods")
    op.drop_table("working_periods")
    op.drop_index(op.f("ix_payments_vip_client_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_external_reference"), table_name="payments")
    op.drop_index(op.f("ix_payments_appointment_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_client_credit_entry_vip_client_id"), table_name="client_credit_entry")
    op.drop_index(op.f("ix_client_credit_entry_source_id"), table_name="client_credit_entry")
    op.drop_index(op.f("ix_client_credit_entry_related_entry_id"), table_name="client_credit_entry")
    op.drop_table("client_credit_entry")
    op.drop_table("calendar_settings")
    op.drop_index(op.f("ix_calendar_exceptions_calendar_of_user"), table_name="calendar_exceptions")
    op.drop_table("calendar_exceptions")
    op.drop_index(op.f("ix_audit_logs_entity_name"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_appointments_vip_client_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_user_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_referral_code"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_project_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_is_posted_on_socials"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_deposit_confirmed_at"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_color"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_client_phone"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_client_email"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_appointment_type"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_vip_client_phone"), table_name="vip_client")
    op.drop_index(op.f("ix_vip_client_email"), table_name="vip_client")
    op.drop_index(op.f("ix_vip_client_client_code"), table_name="vip_client")
    op.drop_table("vip_client")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # PostgreSQL enum types are schema objects independent from their tables.
    # Alembic autogenerate drops the tables but leaves these types behind, which
    # would make a later `upgrade head` fail with DuplicateObject.
    for enum_name in (
        "appointment_status_enum",
        "appointment_type_enum",
        "auditactortype",
        "calendar_exception_type_enum",
        "client_credit_source_type",
        "payment_method_enum",
        "payment_purpose_enum",
        "refund_status_enum",
        "refund_method_enum",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
    # ### end Alembic commands ###
